apiVersion: v2
name: observability-opensearch

description: Opensearch umbrella chart
type: application

version: 1.0.0
appVersion: "2.0.1"

dependencies:
  - name: opensearch
    alias: opensearch-master
    version: 2.0.1
    repository: https://opensearch-project.github.io/helm-charts/
  - name: opensearch
    alias: opensearch-data-az1
    version: 2.0.1
    repository: https://opensearch-project.github.io/helm-charts/
  - name: opensearch
    alias: opensearch-data-az2
    version: 2.0.1
    repository: https://opensearch-project.github.io/helm-charts/
  - name: opensearch-dashboards
    alias: opensearch-dashboards
    version: 2.0.1
    repository: https://opensearch-project.github.io/helm-charts/
#  - name: logstash
#    alias: logstash
#    version: "7.16.3"
#    repository: https://helm.elastic.co/
#  - name: filebeat
#    alias: filebeat
#    version: "7.16.3"
#    repository: https://helm.elastic.co/