securityPlugin:
  path: "configs/securityPlugin"
  configs:
    - "internal_users.yml"
    - "roles.yml"
    - "roles_mapping.yml"
    - "tenants.yml"

securityPluginConfigs:
  - "internal_users.yml"
  - "roles.yml"
  - "roles_mapping.yml"
  - "tenants.yml"

opensearch-master:
  nameOverride: ""
  fullnameOverride: ""

  clusterName: "observability-opensearch"
  nodeGroup: "master"

  masterService: "observability-opensearch-master"

  roles:
    - master

  replicas: 2
  minimumMasterNodes: 1
  majorVersion: ""

  global:
    dockerRegistry: ""
  image:
    repository: "opensearchproject/opensearch"
    tag: ""
    pullPolicy: "IfNotPresent"
  imagePullSecrets: [ ]

  opensearchHome: /usr/share/opensearch

  config:
    opensearch.yml: |
      cluster.name: observability-opensearch
      network.host: 0.0.0.0

      plugins:
        security:
          ssl:
            transport:
              pemcert_filepath: esnode.pem
              pemkey_filepath: esnode-key.pem
              pemtrustedcas_filepath: root-ca.pem
              enforce_hostname_verification: false
            http:
              enabled: true
              pemcert_filepath: esnode.pem
              pemkey_filepath: esnode-key.pem
              pemtrustedcas_filepath: root-ca.pem
          allow_unsafe_democertificates: true
          allow_default_init_securityindex: true
          authcz:
            admin_dn:
              - CN=kirk,OU=client,O=client,L=test,C=de
          audit.type: internal_opensearch
          enable_snapshot_restore_privilege: true
          check_snapshot_restore_write_privileges: true
          restapi:
            roles_enabled: ["all_access", "security_rest_api_access"]
          system_indices:
            enabled: true
            indices:
              [
                ".opendistro-alerting-config",
                ".opendistro-alerting-alert*",
                ".opendistro-anomaly-results*",
                ".opendistro-anomaly-detector*",
                ".opendistro-anomaly-checkpoints",
                ".opendistro-anomaly-detection-state",
                ".opendistro-reports-*",
                ".opendistro-notifications-*",
                ".opendistro-notebooks",
                ".opendistro-asynchronous-search-response*",
              ]

  extraEnvs:
    - name: node.store.allow_mmap
      value: "false"
    - name: DISABLE_INSTALL_DEMO_CONFIG
      value: "false"
    - name: DISABLE_SECURITY_PLUGIN
      value: "false"
    - name: cluster.routing.allocation.awareness.attributes
      value: "zone"
    - name: cluster.routing.allocation.awareness.force.zone.values
      value: "az1,az2"
  envFrom: [ ]
  secretMounts: [ ]
  hostAliases: [ ]

  podAnnotations: { }
  labels: { }

  opensearchJavaOpts: "-Xmx4G -Xms4G"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "4"
      memory: "5Gi"

  initResources: { }
  sidecarResources: { }

  rbac:
    create: false
    serviceAccountAnnotations: { }
    serviceAccountName: ""
  podSecurityPolicy:
    create: false

  persistence:
    enabled: false
    enableInitChown: true
    labels:
      enabled: false
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    annotations: { }

  extraVolumes: [ ]
  extraVolumeMounts: [ ]

  extraContainers: [ ]
  extraInitContainers: [ ]

  antiAffinityTopologyKey: "kubernetes.io/hostname"
  antiAffinity: "soft"
  nodeAffinity: { }

  topologySpreadConstraints: [ ]
  podManagementPolicy: "Parallel"
  schedulerName: ""

  lifecycle: { }
  keystore: [ ]

  priorityClassName: ""
  enableServiceLinks: true

  networkHost: "0.0.0.0"
  protocol: http
  httpPort: 9200
  transportPort: 9300

  service:
    labels: { }
    labelsHeadless: { }
    headless:
      annotations: { }
    type: ClusterIP
    nodePort: ""
    annotations: { }
    httpPortName: http
    transportPortName: transport
    loadBalancerIP: ""
    loadBalancerSourceRanges: [ ]
    externalTrafficPolicy: ""

  updateStrategy: RollingUpdate
  maxUnavailable: 1
  masterTerminationFix: false
  terminationGracePeriod: 120

  podSecurityContext:
    fsGroup: 1000
    runAsUser: 1000
  fsGroup: ""
  securityContext:
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
    runAsUser: 1000

  securityConfig:
    enabled: true
    path: "/usr/share/opensearch/plugins/opensearch-security/securityconfig"
    actionGroupsSecret:
    configSecret:
    internalUsersSecret: "observability-opensearch-security-plugin"
    rolesSecret: "observability-opensearch-security-plugin"
    rolesMappingSecret: "observability-opensearch-security-plugin"
    tenantsSecret: "observability-opensearch-security-plugin"
    config:
      securityConfigSecret: ""
      dataComplete: false
      data: { }

  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 3
    timeoutSeconds: 2000

  nodeSelector: { }
  tolerations: [ ]

  ingress:
    enabled: false

  networkPolicy:
    create: false
    http:
      enabled: false

  sysctlVmMaxMapCount: 262144
  sysctl:
    enabled: false

  plugins:
    enabled: false
    installList: [ ]

  extraObjects: [ ]

opensearch-data-az1:
  nameOverride: ""
  fullnameOverride: ""

  clusterName: "observability-opensearch"
  nodeGroup: "data-az1"

  masterService: "observability-opensearch-master"

  roles:
    - data

  replicas: 1
  minimumMasterNodes: 1
  majorVersion: ""

  global:
    dockerRegistry: ""
  image:
    repository: "opensearchproject/opensearch"
    tag: ""
    pullPolicy: "IfNotPresent"
  imagePullSecrets: [ ]

  opensearchHome: /usr/share/opensearch

  config:
    opensearch.yml: |
      cluster.name: observability-opensearch
      network.host: 0.0.0.0

      plugins:
        security:
          ssl:
            transport:
              pemcert_filepath: esnode.pem
              pemkey_filepath: esnode-key.pem
              pemtrustedcas_filepath: root-ca.pem
              enforce_hostname_verification: false
            http:
              enabled: true
              pemcert_filepath: esnode.pem
              pemkey_filepath: esnode-key.pem
              pemtrustedcas_filepath: root-ca.pem
          allow_unsafe_democertificates: true
          allow_default_init_securityindex: true
          authcz:
            admin_dn:
              - CN=kirk,OU=client,O=client,L=test,C=de
          audit.type: internal_opensearch
          enable_snapshot_restore_privilege: true
          check_snapshot_restore_write_privileges: true
          restapi:
            roles_enabled: ["all_access", "security_rest_api_access"]
          system_indices:
            enabled: true
            indices:
              [
                ".opendistro-alerting-config",
                ".opendistro-alerting-alert*",
                ".opendistro-anomaly-results*",
                ".opendistro-anomaly-detector*",
                ".opendistro-anomaly-checkpoints",
                ".opendistro-anomaly-detection-state",
                ".opendistro-reports-*",
                ".opendistro-notifications-*",
                ".opendistro-notebooks",
                ".opendistro-asynchronous-search-response*",
              ]

  extraEnvs:
    - name: node.store.allow_mmap
      value: "false"
    - name: DISABLE_INSTALL_DEMO_CONFIG
      value: "false"
    - name: DISABLE_SECURITY_PLUGIN
      value: "false"
    - name: node.attr.zone
      value: "az1"
  envFrom: [ ]
  secretMounts: [ ]
  hostAliases: [ ]

  podAnnotations: { }
  labels: { }

  opensearchJavaOpts: "-Xmx4G -Xms4G"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "4"
      memory: "5Gi"

  initResources: { }
  sidecarResources: { }

  rbac:
    create: false
    serviceAccountAnnotations: { }
    serviceAccountName: ""
  podSecurityPolicy:
    create: false

  persistence:
    enabled: false
    enableInitChown: true
    labels:
      enabled: false
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    annotations: { }

  extraVolumes: [ ]
  extraVolumeMounts: [ ]

  extraContainers: [ ]
  extraInitContainers: [ ]

  antiAffinityTopologyKey: "kubernetes.io/hostname"
  antiAffinity: "soft"
  nodeAffinity: { }
  #    requiredDuringSchedulingIgnoredDuringExecution:
  #      nodeSelectorTerms:
  #        - matchExpressions:
  #            - key: topology.kubernetes.io/zone
  #              operator: In
  #              values: [ "az1" ]

  topologySpreadConstraints: [ ]
  podManagementPolicy: "Parallel"

  schedulerName: ""
  lifecycle: { }

  priorityClassName: ""
  keystore: [ ]
  enableServiceLinks: true

  networkHost: "0.0.0.0"
  protocol: http
  httpPort: 9200
  transportPort: 9300

  service:
    labels: { }
    labelsHeadless: { }
    headless:
      annotations: { }
    type: ClusterIP
    nodePort: ""
    annotations: { }
    httpPortName: http
    transportPortName: transport
    loadBalancerIP: ""
    loadBalancerSourceRanges: [ ]
    externalTrafficPolicy: ""

  updateStrategy: RollingUpdate
  maxUnavailable: 1
  masterTerminationFix: false
  terminationGracePeriod: 120

  podSecurityContext:
    fsGroup: 1000
    runAsUser: 1000
  fsGroup: ""

  securityContext:
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
    runAsUser: 1000

  securityConfig:
    enabled: true
    path: "/usr/share/opensearch/plugins/opensearch-security/securityconfig"
    actionGroupsSecret:
    configSecret:
    internalUsersSecret: "observability-opensearch-security-plugin"
    rolesSecret: "observability-opensearch-security-plugin"
    rolesMappingSecret: "observability-opensearch-security-plugin"
    tenantsSecret: "observability-opensearch-security-plugin"
    config:
      securityConfigSecret: ""
      dataComplete: false
      data: { }

  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 3
    timeoutSeconds: 2000

  nodeSelector: { }
  tolerations: [ ]

  ingress:
    enabled: false

  networkPolicy:
    create: false
    http:
      enabled: false

  sysctlVmMaxMapCount: 262144
  sysctl:
    enabled: false

  plugins:
    enabled: false
    installList: [ ]

  extraObjects: [ ]

opensearch-data-az2:
  nameOverride: ""
  fullnameOverride: ""

  clusterName: "observability-opensearch"
  nodeGroup: "data-az2"

  masterService: "observability-opensearch-master"

  roles:
    - data

  replicas: 1
  minimumMasterNodes: 1
  majorVersion: ""

  global:
    dockerRegistry: ""
  image:
    repository: "opensearchproject/opensearch"
    tag: ""
    pullPolicy: "IfNotPresent"
  imagePullSecrets: [ ]

  opensearchHome: /usr/share/opensearch

  config:
    opensearch.yml: |
      cluster.name: observability-opensearch
      network.host: 0.0.0.0

      plugins:
        security:
          ssl:
            transport:
              pemcert_filepath: esnode.pem
              pemkey_filepath: esnode-key.pem
              pemtrustedcas_filepath: root-ca.pem
              enforce_hostname_verification: false
            http:
              enabled: true
              pemcert_filepath: esnode.pem
              pemkey_filepath: esnode-key.pem
              pemtrustedcas_filepath: root-ca.pem
          allow_unsafe_democertificates: true
          allow_default_init_securityindex: true
          authcz:
            admin_dn:
              - CN=kirk,OU=client,O=client,L=test,C=de
          audit.type: internal_opensearch
          enable_snapshot_restore_privilege: true
          check_snapshot_restore_write_privileges: true
          restapi:
            roles_enabled: ["all_access", "security_rest_api_access"]
          system_indices:
            enabled: true
            indices:
              [
                ".opendistro-alerting-config",
                ".opendistro-alerting-alert*",
                ".opendistro-anomaly-results*",
                ".opendistro-anomaly-detector*",
                ".opendistro-anomaly-checkpoints",
                ".opendistro-anomaly-detection-state",
                ".opendistro-reports-*",
                ".opendistro-notifications-*",
                ".opendistro-notebooks",
                ".opendistro-asynchronous-search-response*",
              ]

  extraEnvs:
    - name: node.store.allow_mmap
      value: "false"
    - name: DISABLE_INSTALL_DEMO_CONFIG
      value: "false"
    - name: DISABLE_SECURITY_PLUGIN
      value: "false"
    - name: node.attr.zone
      value: "az2"
  envFrom: [ ]
  secretMounts: [ ]
  hostAliases: [ ]

  podAnnotations: { }
  labels: { }

  opensearchJavaOpts: "-Xmx4G -Xms4G"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "4"
      memory: "5Gi"

  initResources: { }
  sidecarResources: { }

  rbac:
    create: false
    serviceAccountAnnotations: { }
    serviceAccountName: ""
  podSecurityPolicy:
    create: false

  persistence:
    enabled: false
    enableInitChown: true
    labels:
      enabled: false
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    annotations: { }

  extraVolumes: [ ]
  extraVolumeMounts: [ ]

  extraContainers: [ ]
  extraInitContainers: [ ]

  antiAffinityTopologyKey: "kubernetes.io/hostname"
  antiAffinity: "soft"
  nodeAffinity: { }
  #    requiredDuringSchedulingIgnoredDuringExecution:
  #      nodeSelectorTerms:
  #        - matchExpressions:
  #            - key: topology.kubernetes.io/zone
  #              operator: In
  #              values: [ "az1" ]

  topologySpreadConstraints: [ ]
  podManagementPolicy: "Parallel"
  schedulerName: ""

  lifecycle: { }
  keystore: [ ]

  priorityClassName: ""
  enableServiceLinks: true

  networkHost: "0.0.0.0"
  protocol: http
  httpPort: 9200
  transportPort: 9300

  service:
    labels: { }
    labelsHeadless: { }
    headless:
      annotations: { }
    type: ClusterIP
    nodePort: ""
    annotations: { }
    httpPortName: http
    transportPortName: transport
    loadBalancerIP: ""
    loadBalancerSourceRanges: [ ]
    externalTrafficPolicy: ""

  updateStrategy: RollingUpdate
  maxUnavailable: 1
  masterTerminationFix: false
  terminationGracePeriod: 120

  podSecurityContext:
    fsGroup: 1000
    runAsUser: 1000
  fsGroup: ""
  securityContext:
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
    runAsUser: 1000

  securityConfig:
    enabled: true
    path: "/usr/share/opensearch/plugins/opensearch-security/securityconfig"
    actionGroupsSecret:
    configSecret:
    internalUsersSecret: "observability-opensearch-security-plugin"
    rolesSecret: "observability-opensearch-security-plugin"
    rolesMappingSecret: "observability-opensearch-security-plugin"
    tenantsSecret: "observability-opensearch-security-plugin"
    config:
      securityConfigSecret: ""
      dataComplete: false
      data: { }

  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 3
    timeoutSeconds: 2000

  nodeSelector: { }
  tolerations: [ ]

  ingress:
    enabled: false

  networkPolicy:
    create: false
    http:
      enabled: false

  sysctlVmMaxMapCount: 262144
  sysctl:
    enabled: false

  plugins:
    enabled: false
    installList: [ ]

  extraObjects: [ ]

opensearch-dashboards:
  nameOverride: ""
  fullnameOverride: "observability-opensearch-dashboards"

  opensearchHosts: "https://observability-opensearch-master-headless:9200"

  replicaCount: 1

  image:
    repository: "opensearchproject/opensearch-dashboards"
    tag: ""
    pullPolicy: "IfNotPresent"

  imagePullSecrets: [ ]

  serviceAccount:
    create: false
    annotations: { }
    name: ""

  rbac:
    create: false

  secretMounts: [ ]
  podAnnotations: { }
  extraEnvs: [ ]
  envFrom: [ ]
  extraVolumes: [ ]
  extraVolumeMounts: [ ]

  extraInitContainers: ""
  extraContainers: ""

  podSecurityContext: { }

  securityContext:
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
    runAsUser: 1000

  config:
    opensearch_dashboards.yml: |
      opensearch.ssl.verificationMode: none
      
      opensearch.username: kibanaserver
      opensearch.password: kibanaserver
      
      opensearch.requestHeadersWhitelist: [authorization, securitytenant]
      
      opensearch_security.multitenancy.enabled: true
      opensearch_security.multitenancy.tenants.enable_global: false
      opensearch_security.multitenancy.tenants.enable_private: false
      opensearch_security.multitenancy.tenants.preferred: [Private, Global]
      opensearch_security.readonly_mode.roles: [kibana_read_only]
      opensearch_security.cookie.secure: false

  priorityClassName: ""

  opensearchAccount:
    secret: ""
    keyPassphrase:
      enabled: false

  labels: { }

  hostAliases: [ ]

  serverHost: "0.0.0.0"

  service:
    type: ClusterIP
    port: 5601
    loadBalancerIP: ""
    nodePort: ""
    labels: { }
    annotations: { }
    loadBalancerSourceRanges: [ ]
    httpPortName: http

  ingress:
    enabled: false
    annotations: { }
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            backend:
              serviceName: chart-example.local
              servicePort: 80
    tls: [ ]

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "4"
      memory: "5Gi"

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

  updateStrategy:
    type: "Recreate"

  nodeSelector: { }
  tolerations: [ ]
  affinity: { }

  extraObjects: [ ]