---
_meta:
  type: "rolesmapping"
  config_version: 2

all_access:
  reserved: true
  backend_roles:
    - "admin"

kibana_server:
  reserved: true
  users:
    - "kibanaserver"

seemscloud-global:
  reserved: false
  backend_roles:
    - "seemscloud-observability"
    - "seemscloud-analytics"

seemscloud-observability:
  reserved: false
  backend_roles:
    - "seemscloud-observability"

seemscloud-analytics:
  reserved: false
  backend_roles:
    - "seemscloud-analytics"