---
_meta:
  type: "roles"
  config_version: 2

kibana_read_only:
  reserved: true
  hidden: true

security_rest_api_access:
  reserved: true
  hidden: true

alerting_read_access:
  reserved: true
  hidden: true

alerting_ack_alerts:
  reserved: true
  hidden: true

alerting_full_access:
  reserved: true
  hidden: true

anomaly_read_access:
  reserved: true
  hidden: true

anomaly_full_access:
  reserved: true
  hidden: true

notebooks_read_access:
  reserved: true
  hidden: true

notebooks_full_access:
  reserved: true
  hidden: true

observability_read_access:
  reserved: true
  hidden: true

observability_full_access:
  reserved: true
  hidden: true

reports_instances_read_access:
  reserved: true
  hidden: true

reports_read_access:
  reserved: true
  hidden: true

reports_full_access:
  reserved: true
  hidden: true

asynchronous_search_full_access:
  reserved: true
  hidden: true

asynchronous_search_read_access:
  reserved: true
  hidden: true

index_management_full_access:
  reserved: true
  hidden: true

cross_cluster_replication_leader_full_access:
  reserved: true
  hidden: true

cross_cluster_replication_follower_full_access:
  reserved: true
  hidden: true

ml_read_access:
  reserved: true
  hidden: true

ml_full_access:
  reserved: true
  hidden: true

seemscloud-observability:
  reserved: false
  cluster_permissions:
    - "indices:data/read/mget"
    - "indices:admin/aliases/get"
    - "indices:data/write/bulk"
    - "cluster:monitor/state"
    - "cluster:admin/opensearch/notifications/configs/get"
    - "cluster:admin/opensearch/notifications/features"
    - "cluster:admin/opensearch/notifications/configs/create"
    - "cluster:admin/opensearch/notifications/configs/delete"
    - "cluster:admin/opendistro/alerting/destination/get"
    - "cluster:admin/opendistro/alerting/monitor/get"
    - "cluster:admin/opendistro/alerting/monitor/search"
    - "cluster:admin/opendistro/alerting/monitor/execute"
    - "cluster:admin/opendistro/alerting/monitor/write"
    - "cluster:admin/opendistro/alerting/alerts/get"
    - "cluster:monitor/nodes/info"
  index_permissions:
    - index_patterns:
        - "observability-*"
      allowed_actions:
        - "indices:admin/resolve/index"
        - "indices:data/read/field_caps"
        - "indices:data/read/search"
    - index_patterns:
        - "*"
      allowed_actions:
        - "indices:admin/aliases/get"
        - "indices:monitor/stats"
        - "indices:monitor/settings/get"
  tenant_permissions:
    - tenant_patterns:
        - "seemscloud-observability"
      allowed_actions:
        - "kibana_all_write"