apiVersion: v1
kind: Secret
metadata:
  name: {{ include "observability-opensearch.fullname" $ }}-security-plugin
  labels:
    {{- include "observability-opensearch.labels" $ | nindent 4 }}
type: Opaque
data:
{{ ($.Files.Glob "configs/securityPlugin/*" ).AsSecrets | indent 2 }}