{{- $securityPluginConfigs := printf "%s/%s/%s/*" "configs" .Values.environment "securityPlugin" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "observability-opensearch.fullname" $ }}-securityconfig
  labels:
    {{- include "observability-opensearch.labels" $ | nindent 4 }}
type: Opaque
data:
{{ ($.Files.Glob $securityPluginConfigs ).AsSecrets | indent 2 }}